from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.setEnabled(True)
        Form.resize(352, 548)
        Form.setMinimumSize(QtCore.QSize(352, 548))
        Form.setMaximumSize(QtCore.QSize(352, 548))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_1 = QtWidgets.QGroupBox(Form)
        self.groupBox_1.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox_1.setObjectName("groupBox_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_1 = QtWidgets.QLabel(self.groupBox_1)
        self.label_1.setObjectName("label_1")
        self.gridLayout_2.addWidget(self.label_1, 0, 0, 1, 1)
        self.lineEdit_1 = QtWidgets.QLineEdit(self.groupBox_1)
        self.lineEdit_1.setEnabled(True)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.gridLayout_2.addWidget(self.lineEdit_1, 0, 1, 1, 2)
        self.pushButton_1 = QtWidgets.QPushButton(self.groupBox_1)
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout_2.addWidget(self.pushButton_1, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_1)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 2)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_1)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_2.addWidget(self.spinBox, 1, 2, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 2, 0, 1, 4)
        self.verticalLayout.addWidget(self.groupBox_1)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 220))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 2)
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.areaContent = QtWidgets.QWidget()
        self.areaContent.setGeometry(QtCore.QRect(0, 0, 308, 81))
        self.areaContent.setObjectName("areaContent")
        self.scrollArea.setWidget(self.areaContent)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 2)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 4, 0, 1, 2)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 120))
        self.textBrowser.setAutoFillBackground(False)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "XML парсер"))
        self.groupBox_1.setTitle(_translate("Form", "Парсинг XML файла"))
        self.label_1.setText(_translate("Form", "XML файл"))
        self.pushButton_1.setText(_translate("Form", "Выбрать"))
        self.label_2.setText(_translate("Form", "Регион субъекта"))
        self.pushButton_2.setText(_translate("Form", "Выполнить"))
        self.groupBox_2.setTitle(_translate("Form", "Конструктор запросов"))
        self.pushButton.setText(_translate("Form", "Удалить"))
        self.pushButton_4.setText(_translate("Form", "Выполнить"))
        self.pushButton_3.setText(_translate("Form", "Добавить"))
