from sqlalchemy import Column, Integer, String, Boolean
from .base import Base

class RKN(Base):
    __tablename__ = "RKN"

    id = Column(Integer, primary_key=True)
    os_name = Column(String(250))
    place_id = Column(Integer)
    fias_guid = Column(String(250))
    region_code = Column(Integer)
    region_name = Column(String(250))
    city = Column(String(250))
    rayon = Column(String(250))
    place = Column(String(250))
    is_local_station = Column(Boolean)
    local_station_payphone_count = Column(Integer)
    is_vnz = Column(Boolean)
    is_mgmn = Column(Boolean)
    is_pd = Column(Boolean)
    pd_max_transfer_speed = Column(Integer)
    pd_type = Column(String(250))
    pd_min_speed = Column(Integer)
    pd_min_type = Column(String(250))
    is_tm = Column(Boolean)
    tm_min_speed = Column(Integer)
    tm_min_type = Column(String(250))
    tm_max_access_speed = Column(Integer)
    tm_type = Column(String(250))
    gsm_type = Column(String(250))
    is_umts = Column(Boolean)
    is_lte = Column(Boolean)
    is_nmt = Column(Boolean)
    is_cdma = Column(Boolean)
    is_etv = Column(Boolean)
    etv_d_channel_cnt = Column(Integer)
    etv_a_channel_cnt = Column(Integer)
    is_rv = Column(Boolean)
    rv_d_channel_cnt = Column(Boolean)
    rv_a_channel_cnt = Column(Integer)
    ktv_channel_cnt = Column(Integer)
    ps_post_office_count = Column(Integer)
    payphone_count = Column(Integer)
    is_ps = Column(Boolean)
    ps_com_dep_cnt = Column(Integer)
    pkd_count = Column(Integer)
    pdk_job_cnt = Column(Integer)
    ap_cnt = Column(Integer)
    ap_min_speed = Column(String(250))
